basePath: /v1
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a server for Insider Case Study API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Insider Case Study API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: Welcome to Trendbox POS API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Welcome API
      tags:
      - Health Check
swagger: "2.0"
